name: Deploy travel.mytune.in

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v7

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: pdo_sqlite, fileinfo

    - name: Install Composer Dependencies
      run: composer install --optimize-autoloader --no-dev

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '22'

    - name: Install NPM & Build Vite Assets
      run: |
        npm ci
        npm run build

    - name: Sync Files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.4.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /travel_app/
